// ============================================================================
// Matematik Dersi Kazanim Verileri
// OSYM 2026 / MEB Ortaogretim Matematik Dersi Ogretim Programi
// Auto-generated from PDF extraction
// ============================================================================

export interface KazanimDetail {
  code: string;
  subTopicName: string;
  description: string;
  details: string[];
  isKeyKazanim: boolean;
}

export interface TopicEntry {
  examType: "TYT" | "AYT";
  subject: string;
  topicKey: string;
  topicName: string;
  gradeLevel: number;
  learningArea: string;
  sortOrder: number;
  kazanimlar: KazanimDetail[];
}

export function getMatematikTopics(): TopicEntry[] {
  return [
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "mantik",
      topicName: 'Mantık',
      gradeLevel: 9,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 1,
      kazanimlar: [
        {
          code: '9.1.1.1',
          subTopicName: 'Önermeler ve Bileşik Önermeler',
          description: 'Önermeyi, önermenin doğruluk değerini, iki önermenin denkliğini ve önermenin değilini açıklar.',
          details: [
            'Boole ve Leibniz\'in çalışmalarına yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.1.1.2',
          subTopicName: 'Önermeler ve Bileşik Önermeler',
          description: 'Bileşik önermeyi örneklerle açıklar, "ve, veya, ya da" bağlaçları ile kurulan bileşik önermelerin özelliklerini ve De Morgan kurallarını doğruluk tablosu kullanarak gösterir.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '9.1.1.3',
          subTopicName: 'Önermeler ve Bileşik Önermeler',
          description: 'Koşullu önermeyi ve iki yönlü koşullu önermeyi açıklar.',
          details: [
            'a) Koşullu önermenin karşıtı, tersi, karşıt tersi verilir.',
            'b) p ⇒ q ≡ p\' ∨ q olduğu doğruluk tablosu yardımıyla gösterilir.',
            'c) "ve, veya, ya da, ise" bağlaçları kullanılarak verilen, en fazla üç önerme içeren ve en fazla dört bileşenli bileşik önermelere denk basit önermeler buldurulur.',
            'ç) p ⇔ q ≡ (p ⇒ q) ∧ (q ⇒ p) olduğu doğruluk tablosu ile gösterilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.1.1.4',
          subTopicName: 'Önermeler ve Bileşik Önermeler',
          description: 'Her (∀) ve bazı (∃) niceleyicilerini örneklerle açıklar.',
          details: [
            'Sözel olarak verilen ve niceleyici içeren açık önermeler, sembolik mantık diliyle; sembolik mantık diliyle verilen ve niceleyici içeren açık önermeler de sözel olarak ifade edilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.1.1.5',
          subTopicName: 'Önermeler ve Bileşik Önermeler',
          description: 'Tanım, aksiyom, teorem ve ispat kavramlarını açıklar.',
          details: [
            'Bir teoremin hipotezi ve hükmü belirtilir.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "kumeler",
      topicName: 'Kümeler',
      gradeLevel: 9,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 2,
      kazanimlar: [
        {
          code: '9.2.1.1',
          subTopicName: 'Kümelerde Temel Kavramlar',
          description: 'Kümeler ile ilgili temel kavramlar hatırlatılır.',
          details: [
            'a) Kümelerle ilgili gerçek hayattan örneklere yer verilir.',
            'b) Kümelerin farklı gösterimlerine yer verilir.',
            'c) Cantor\'un çalışmalarına yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.2.1.2',
          subTopicName: 'Kümelerde Temel Kavramlar',
          description: 'Alt kümeyi kullanarak işlemler yapar.',
          details: [
            'a) Alt küme kavramı ve özellikleri ele alınır.',
            'b) Alt küme kavramıyla ilgili gerçek hayattan örneklere yer verilir.',
            'c) Kombinasyon gerektiren problemlere girilmez.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.2.1.3',
          subTopicName: 'Kümelerde Temel Kavramlar',
          description: 'İki kümenin eşitliğini kullanarak işlemler yapar.',
          details: [
            'a) İki kümenin eşitliği kavramı alt küme ile ilişkilendirilir.',
            'b) Denk küme kavramı verilmez.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.2.2.1',
          subTopicName: 'Kümelerde İşlemler',
          description: 'Kümelerde birleşim, kesişim, fark, tümleme işlemleri yardımıyla problemler çözer.',
          details: [
            'a) Kümelerin birleşim, kesişim, fark ve tümleme işlemlerinin özellikleri verilir.',
            'b) Ayrık küme kavramına yer verilir.',
            'c) En fazla üç kümenin birleşiminin eleman sayısını veren ilişkiler üzerinde durulur.',
            'ç) Kümelerle yapılan işlemler ve sembolik mantıkta kullanılan sembol, gösterim ve bunlarla ifade edilen işlemler arasında aşağıdaki ilişkilendirmeler yapılır.',
            'd) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.2.2.2',
          subTopicName: 'Kümelerde İşlemler',
          description: 'İki kümenin kartezyen çarpımıyla ilgili işlemler yapar.',
          details: [
            'a) Sıralı ikili ve sıralı ikililerin eşitliği örneklerle açıklanır.',
            'b) Kartezyen çarpımın eleman sayısı buldurulur.',
            'c) Sadece sonlu sayıda elemanı olan kümelerin kartezyen çarpımlarının grafik çizimi yapılır.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "denklemler_esitsizlikler",
      topicName: 'Denklemler ve Eşitsizlikler',
      gradeLevel: 9,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 3,
      kazanimlar: [
        {
          code: '9.3.1.1',
          subTopicName: 'Sayı Kümeleri',
          description: 'Sayı kümelerini birbiriyle ilişkilendirir.',
          details: [
            'a) Doğal sayı, tam sayı, rasyonel sayı, irrasyonel sayı ve gerçek sayı kümelerinin sembolleri tanıtılarak bu sayı kümeleri arasındaki ilişki üzerinde durulur.',
            'b) √2, √3, √5 gibi sayıların doğrusundaki yeri belirlenir.',
            'c) Gerçek sayılar kümesinde toplama ve çarpma işlemlerinin özellikleri üzerinde durulur.',
            'ç) ℝ nin geometrik temsilinin sayı doğrusu, ℝ×ℝ nin geometrik temsilinin de kartezyen koordinat sistemi olduğu vurgulanır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.3.2.1',
          subTopicName: 'Bölünebilme Kuralları',
          description: 'Tam sayılarda bölünebilme kurallarıyla ilgili problemler çözer.',
          details: [
            '2, 3, 4, 5, 8, 9, 10, 11 ile bu sayılardan elde edilen 6, 12, 15 gibi sayıların bölünebilme kuralları ele alınır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.3.2.2',
          subTopicName: 'Bölünebilme Kuralları',
          description: 'Tam sayılarda EBOB ve EKOK ile ilgili uygulamalar yapar.',
          details: [
            'a) Gerçek hayat problemlerine yer verilir.',
            'b) Elektronik tablolarda bulunan EBOB ve EKOK fonksiyonlarından yararlanılır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.3.2.3',
          subTopicName: 'Bölünebilme Kuralları',
          description: 'Gerçek hayatta periyodik olarak tekrar eden durumları içeren problemleri çözer.',
          details: [
            'Modüler aritmetiğe girilmeden periyodik durum içeren problemlere yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.3.3.1',
          subTopicName: 'Birinci Dereceden Denklemler ve Eşitsizlikler',
          description: 'Gerçek sayılar kümesinde aralık kavramını açıklar.',
          details: [
            'a) Açık, kapalı ve yarı açık aralık kavramları ile bunların gösterimleri üzerinde durulur.',
            'b) Aralıkların kartezyen çarpımlarına yer verilmez.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.3.3.2',
          subTopicName: 'Birinci Dereceden Denklemler ve Eşitsizlikler',
          description: 'Birinci dereceden bir bilinmeyenli denklem ve eşitsizliklerin çözüm kümelerini bulur.',
          details: [
            'a) Birinci dereceden bir bilinmeyenli denklem ve eşitsizliklerin çözümü hatırlatılır.',
            'b) Harezmi\'nin denklemler konusundaki çalışmalarına yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.3.3.3',
          subTopicName: 'Birinci Dereceden Denklemler ve Eşitsizlikler',
          description: 'Mutlak değer içeren birinci dereceden bir bilinmeyenli denklem ve eşitsizliklerin çözüm kümelerini bulur.',
          details: [
            'a) Bir gerçek sayının mutlak değeri hatırlatılarak mutlak değer özellikleri verilir.',
            'b) İkiden çok mutlak değer içeren denklem ve eşitsizliklere girilmez.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.3.3.4',
          subTopicName: 'Birinci Dereceden Denklemler ve Eşitsizlikler',
          description: 'Birinci dereceden iki bilinmeyenli denklem ve eşitsizlik sistemlerinin çözüm kümelerini bulur.',
          details: [
            'a) Birinci dereceden iki bilinmeyenli denklem sistemlerinin çözüm kümeleri bulunurken yerine koyma, yok etme veya grafikle çözüm yöntemlerinden faydalanılır.',
            'b) Birinci dereceden iki bilinmeyenli denklem ve eşitsizlik sistemlerinin çözümü, analitik düzlemde gösterilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.3.4.1',
          subTopicName: 'Üslü İfadeler ve Denklemler',
          description: 'Üslü ifadeleri içeren denklemleri çözer.',
          details: [
            'a) Üslü ifade kavramı hatırlatılır.',
            'b) Bir gerçek sayının tam sayı kuvveti ile ilgili uygulamalar yapılır.',
            'c) Üslü ifadelerin özellikleri üzerinde durulur.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.3.4.2',
          subTopicName: 'Üslü İfadeler ve Denklemler',
          description: 'Köklü ifadeleri içeren denklemleri çözer.',
          details: [
            'a) Köklü ifadelerin özellikleri üzerinde durulur.',
            'b) x ∈ ℝ⁺ ve m, n ∈ ℤ⁺ için n > 1 olmak üzere ⁿ√xᵐ = x^(m/n) olduğu vurgulanarak köklü ifadeler ve üslü ifadeler arasındaki ilişkiler üzerinde durulur.',
            'c) En çok iki terimli köklü ifadelerin eşleniklerine yer verilir.',
            'ç) Köklü ifadelerde sonsuza giden iç içe köklerle yapılan işlemlere yer verilmez.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.3.5.1',
          subTopicName: 'Denklemler ve Eşitsizliklerle İlgili Uygulamalar',
          description: 'Oran ve orantı kavramlarını kullanarak problemler çözer.',
          details: [
            'a) Oran, orantı, doğru orantı, ters orantı kavramları ile oran ve orantıya ait özellikler hatırlatılır.',
            'b) Altın oran tanıtılarak gerçek hayattan örnekler verilir ancak hesaplama yöntemlerine yer verilmez.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.3.5.2',
          subTopicName: 'Denklemler ve Eşitsizliklerle İlgili Uygulamalar',
          description: 'Denklemler ve eşitsizlikler ile ilgili problemler çözer.',
          details: [
            'a) Gerçek hayat durumlarını temsil eden sözel ifadelerdeki ilişkilerin cebirsel, grafiksel ve sayısal temsilleri ile ilgili uygulamalar yapılır.',
            'b) Farklı problem çözme stratejilerinin uygulanmasını gerektiren oran, orantı kavramlarının kullanıldığı problemlere (örneğin elektrik, su vb. fatura ve ödemeler; sayı, kesir, yaş, işçi, alım-satım, kâr-zarar, yüzde ve karışım problemleri; hız ve hareket (hız kavramı, sabit hız, ortalama hız, birimler arası dönüşüm (km/sa., m/sn.)) yer verilir; faiz, havuz, saat problemlerine girilmez.',
            'c) Rutin olmayan problem türlerine de yer verilerek farklı problem çözme stratejilerinin uygulanmasına imkân verilir.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "ucgenler",
      topicName: 'Üçgenler',
      gradeLevel: 9,
      learningArea: 'GEOMETRİ',
      sortOrder: 4,
      kazanimlar: [
        {
          code: '9.4.1.1',
          subTopicName: 'Üçgenlerde Temel Kavramlar',
          description: 'Üçgende açı özellikleri ile ilgili işlemler yapar.',
          details: [
            'a) Kültür ve medeniyetimizden geometrinin tarihsel gelişim sürecine katkı sağlamış bilim insanları ve bilim insanlarının yaptığı çalışmalar tanıtılır. Mustafa Kemal Atatürk\'ün geometri üzerine yaptığı çalışmalardan bahsedilir.',
            'b) Açı çeşitleri ve paralel iki doğrunun bir kesenle yaptığı açılar hatırlatılır.',
            'c) Üçgende sadece iç ve dış açı özelliklerinin kullanıldığı sorulara yer verilir. İkizkenar ve eşkenar üçgenin açı özellikleri üzerinde durulur.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.4.1.2',
          subTopicName: 'Üçgenlerde Temel Kavramlar',
          description: 'Üçgenin kenar uzunlukları ile bu kenarların karşılarındaki açıların ölçülerini ilişkilendirir.',
          details: [
            'a) Bir üçgende en uzun kenarın karşısındaki açının ölçüsünün en büyük olduğu ve bunun tersinin de doğru olduğu gösterilir.',
            'b) Dinamik matematik yazılımları kullanılarak oluşturulan üçgenlerin kenar ve açıları arasındaki ilişkinin gözlemlenmesi sağlanır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.1.3',
          subTopicName: 'Üçgenlerde Temel Kavramlar',
          description: 'Uzunlukları verilen üç doğru parçasının hangi durumlarda üçgen oluşturduğunu değerlendirir.',
          details: [
            'a) İki kenar uzunluğu verilen bir üçgenin üçüncü kenar uzunluğunun hangi aralıkta değerler alabileceğine ilişkin uygulamalar yapılır.',
            'b) Dinamik matematik yazılımlarından yararlanılarak hangi durumlarda üçgen oluşacağının test edilmesi sağlanır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.2.1',
          subTopicName: 'Üçgenlerde Eşlik ve Benzerlik',
          description: 'İki üçgenin eş olması için gerekli olan asgari koşulları değerlendirir.',
          details: [
            'a) İki üçgenin eşliği hatırlatılır.',
            'b) Kenar-Açı-Kenar (K.A.K.), Açı-Kenar-Açı (A.K.A.), Kenar-Kenar-Kenar (K.K.K.) eşlik kuralları, ölçümler yapılarak oluşturulur.',
            'c) Eş üçgenlerin karşılıklı yardımcı elemanlarının da eş olduğu gösterilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.4.2.2',
          subTopicName: 'Üçgenlerde Eşlik ve Benzerlik',
          description: 'İki üçgenin benzer olması için gerekli olan asgari koşulları değerlendirir.',
          details: [
            'a) Kenar-Açı-Kenar (K.A.K.), Kenar-Kenar-Kenar (K.K.K.) ve Açı-Açı (A.A.) benzerlik kuralları, ölçümler yapılarak oluşturulur.',
            'b) Eşlik ile benzerlik arasındaki ilişki incelenir.',
            'c) Benzer üçgenlerin karşılıklı yardımcı elemanlarının da aynı benzerlik oranına sahip olduğu gösterilir.',
            'ç) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.2.3',
          subTopicName: 'Üçgenlerde Eşlik ve Benzerlik',
          description: 'Üçgenin bir kenarına paralel ve diğer iki kenarı kesecek şekilde çizilen doğrunun ayırdığı doğru parçaları arasındaki ilişkiyi kurar.',
          details: [
            'Thales\'in çalışmalarına yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.2.4',
          subTopicName: 'Üçgenlerde Eşlik ve Benzerlik',
          description: 'Üçgenlerin benzerliği ile ilgili problemler çözer.',
          details: [
            'Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.3.1',
          subTopicName: 'Üçgenin Yardımcı Elemanları',
          description: 'Üçgenin iç ve dış açıortaylarının özelliklerini elde eder.',
          details: [
            'a) Açıortay üzerinde alınan bir noktadan açının kollarına indirilen dikmelerin uzunluklarının eşit olduğu gösterilir.',
            'b) İç ve dış açıortay uzunlukları formülle hesaplatılmaz.',
            'c) Açıortay özelliklerinin gösteriminde pergel-cetvelden yararlanılır.',
            'ç) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.4.3.2',
          subTopicName: 'Üçgenin Yardımcı Elemanları',
          description: 'Üçgenin kenarortaylarının özelliklerini elde eder.',
          details: [
            'a) Kenarortayların kesiştiği nokta ile bu noktanın kenarortay üzerinde ayırdığı parçalar arasındaki ilişki üzerinde durulur.',
            'b) Kenarortayların kesiştiği noktanın, üçgenin ağırlık merkezi olduğuna ve üçgenin ağırlık merkeziyle ilgili özelliklerine yer verilir.',
            'c) Dik üçgende, hipotenüse ait kenarortay uzunluğunun hipotenüs uzunluğunun yarısı olduğu gösterilir.',
            'ç) Kenarortay uzunluğu formülle hesaplatılmaz.',
            'd) Pergel-cetvel kullanarak veya bilgi ve iletişim teknolojileri yardımıyla üçgen üzerinde değişiklikler yapılarak ve üçgen çeşitlerine bağlı olarak değişikliklerin kenarortaylar üzerindeki etkisi gözlemlenir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.3.3',
          subTopicName: 'Üçgenin Yardımcı Elemanları',
          description: 'Üçgenin kenar orta dikmelerinin bir noktada kesiştiğini gösterir.',
          details: [
            'a) Bir doğru parçasının orta dikmesi üzerinde alınan her noktanın, doğru parçasının uç noktalarına eşit uzaklıkta olduğu ve bunun karşıtının da doğru olduğu gösterilir.',
            'b) Pergel-cetvel veya bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.3.4',
          subTopicName: 'Üçgenin Yardımcı Elemanları',
          description: 'Üçgenin çeşidine göre yüksekliklerinin kesiştiği noktanın konumunu belirler.',
          details: [
            'a) Pergel-cetvel kullanarak veya bilgi ve iletişim teknolojileri yardımıyla bir üçgenin yüksekliklerini çizerek kesişimleri üzerinde durulur. Farklı üçgen çeşitleri üzerinde örnekler yapılır.',
            'b) İkizkenar üçgenin tabanında alınan bir noktadan kenarlara çizilen dikmelerin uzunlukları toplamı ile üçgenin eş olan kenarlarına ait yükseklik arasındaki ilişki bulunur.',
            'c) Eşkenar üçgen içerisinde alınan bir noktadan kenarlara indirilen dikmelerin uzunlukları toplamı ile üçgenin yüksekliği arasındaki ilişki bulunur.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.4.1',
          subTopicName: 'Dik Üçgen ve Trigonometri',
          description: 'Dik üçgende Pisagor teoremini elde ederek problemler çözer.',
          details: [
            'a) Teorem elde edilirken model çeşitliliğine yer verilir.',
            'b) Gerçek hayat problemlerine yer verilir.',
            'c) Pythagoras\'ın çalışmalarına yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.4.4.2',
          subTopicName: 'Dik Üçgen ve Trigonometri',
          description: 'Öklid teoremini elde ederek problemler çözer.',
          details: [
            'a) Gerçek hayat problemlerine yer verilir.',
            'b) Euclid\'in çalışmalarına yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.4.3',
          subTopicName: 'Dik Üçgen ve Trigonometri',
          description: 'Dik üçgende dar açıların trigonometrik oranlarını hesaplar.',
          details: [
            'a) Bir açının sinüs, kosinüs, tanjant ve kotanjant değerleri dik üçgen üzerinde tanımlanır.',
            'b) Dik üçgende; 30°, 45° ve 60° nin trigonometrik değerleri özel üçgenler yardımıyla hesaplanır.',
            'c) Gerçek hayat problemlerine yer verilir.',
            'ç) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.4.4',
          subTopicName: 'Dik Üçgen ve Trigonometri',
          description: 'Birim çemberi tanımlar ve trigonometrik oranları birim çemberin üzerindeki noktanın koordinatlarıyla ilişkilendirir.',
          details: [
            'a) Sadece 0° ve 180° arasındaki açıların trigonometrik oranları birim çember yardımıyla hesaplatılır.',
            'b) Ebu\'l Vefa ve Giyaseddin Cemşid\'in trigonometrik oranlarla ilgili çalışmalarından bahsedilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '9.4.5.1',
          subTopicName: 'Üçgenin Alanı',
          description: 'Üçgenin alanı ile ilgili problemler çözer.',
          details: [
            'a) Üçgenin alanı, bir kenarı ile bu kenara ait yükseklik kullanılarak hesaplatılır.',
            'b) İki kenarının uzunluğu ve bu kenarlar arasındaki açının ölçüsü verilen üçgenin alanını hesaplar.',
            'c) Aynı yüksekliğe sahip üçgenlerin alanlarıyla tabanları; aynı tabana sahip üçgenlerin alanlarıyla yükseklikleri arasındaki ilişki vurgulanır.',
            'ç) Benzer üçgenlerin alanları ile benzerlik oranları arasındaki ilişki belirtilir.',
            'd) Bilgi ve iletişim teknolojileri yardımıyla alan, taban ve yüksekliği değiştirilen bir üçgenin alanının nasıl değiştiği gözlemlenir.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "veri",
      topicName: 'Veri',
      gradeLevel: 9,
      learningArea: 'VERİ, SAYMA VE OLASILIK',
      sortOrder: 5,
      kazanimlar: [
        {
          code: '9.5.1.1',
          subTopicName: 'Merkezî Eğilim ve Yayılım Ölçüleri',
          description: 'Verileri merkezî eğilim ve yayılım ölçülerini hesaplayarak yorumlar.',
          details: [
            'a) Veri kavramı, kesikli ve sürekli veri çeşitleri verilir.',
            'b) Aritmetik ortalama, ortanca, tepe değer, en büyük değer, en küçük değer ve açıklık kavramları verilir.',
            'c) Alt çeyrek, üst çeyrek ve çeyrekler açıklığına yer verilmez.',
            'ç) Veri sayısı en fazla beş olan veri grupları için standart sapma hesaplanır.',
            'd) Gerçek hayat durumlarında aritmetik ortalama, ortanca, tepe değer kavramları birlikte yorumlanır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.5.2.1',
          subTopicName: 'Verilerin Grafikle Gösterilmesi',
          description: 'Bir veri grubuna ilişkin histogram oluşturur.',
          details: [
            'a) Histogram oluşturulurken veri grubunun açıklığı seçilen grup sayısına bölünür ve aşağıdaki eşitsizliği sağlayan en küçük doğal sayı değeri grup genişliği olarak belirlenir.',
            'b) Veri gruplarının histogramı çizilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '9.5.2.2',
          subTopicName: 'Verilerin Grafikle Gösterilmesi',
          description: 'Gerçek hayat durumunu yansıtan veri gruplarını uygun grafik türleriyle temsil ederek yorumlar.',
          details: [
            'a) İkiden fazla veri grubunun karşılaştırıldığı durumlara da yer verilir.',
            'b) Serpme ve kutu grafiklerine yer verilmez.',
            'c) Grafik türleri bilgi ve iletişim teknolojileri kullanılarak çizilir.',
            'ç) Tasarruf bilinci kazandırmak amacıyla ekmek israfı, su israfı gibi konulara ilişkin veriler kullanılarak grafik oluşturulması sağlanır.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "sayma_olasilik",
      topicName: 'Sayma ve Olasılık',
      gradeLevel: 10,
      learningArea: 'VERİ, SAYMA VE OLASILIK',
      sortOrder: 6,
      kazanimlar: [
        {
          code: '10.1.1.1',
          subTopicName: 'Sıralama ve Seçme',
          description: 'Olayların gerçekleşme sayısını toplama ve çarpma yöntemlerini kullanarak hesaplar.',
          details: [
            'a) Sayma konusunun tarihsel gelişim sürecinden söz edilir ve bu süreçte rol alan Sâbit İbn Kurrâ\'nın çalışmalarına yer verilir.',
            'b) Faktöriyel kavramı verilerek saymanın temel ilkesi ile ilişkilendirilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '10.1.1.2',
          subTopicName: 'Sıralama ve Seçme',
          description: 'n çeşit nesne ile oluşturulabilecek r li dizilişlerin (permütasyonların) kaç farklı şekilde yapılabileceğini hesaplar.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '10.1.1.3',
          subTopicName: 'Sıralama ve Seçme',
          description: 'Sınırlı sayıda tekrarlayan nesnelerin dizilişlerini (permütasyonlarını) açıklayarak problemler çözer.',
          details: [
            'a) En az iki tanesi özdeş olan nesnelerin tüm farklı dizilişlerinin sayısı örnekler/problemler bağlamında ele alınır.',
            'b) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.1.1.4',
          subTopicName: 'Sıralama ve Seçme',
          description: 'n elemanlı bir kümenin r tane elemanının kaç farklı şekilde seçilebileceğini hesaplar.',
          details: [
            'a) Kombinasyon kavramı alt küme sayısı ile ilişkilendirilir.',
            'b) Kombinasyon kavramının aşağıdaki temel özellikleri incelenir: C(n,r) = C(n,n-r) ve C(n,0) + C(n,1) + ... + C(n,n) = 2ⁿ',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.1.1.5',
          subTopicName: 'Sıralama ve Seçme',
          description: 'Pascal üçgenini açıklar.',
          details: [
            'Pascal üçgeninin, aralarında Ömer Hayyam\'ın da bulunduğu Hint, Çin, İslam medeniyetlerindeki matematikçi ve düşünürler tarafından Pascal\'dan çok önceleri ele alındığı; bu çerçevede matematiksel bilginin oluşumunda farklı kültür ve bilim insanlarının rolü vurgulanır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.1.1.6',
          subTopicName: 'Sıralama ve Seçme',
          description: 'Binom açılımını yapar.',
          details: [
            'a) Binom açılımı Pascal üçgeni ile ilişkilendirilir.',
            'b) Sadece iki terimli ifadelerin açılımı ele alınır.',
            'c) Binom formülü ile ilgili örnekler yapılır ancak (ax + by)ⁿ açılımında n ∈ ℕ, a,b ∈ ℚ\' şeklindeki örneklere yer verilmez.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.1.2.1',
          subTopicName: 'Basit Olayların Olasılıkları',
          description: 'Örnek uzay, deney, çıktı, bir olayın tümleyeni, kesin olay, imkânsız olay, ayrık olay ve ayrık olmayan olay kavramlarını açıklar.',
          details: [
            'a) Örnek uzay, deney, çıktı kavramları eş olası durumlardan yola çıkılarak eş olası olmayan durumlar için de örneklendirilir ve tanımlanır.',
            'b) Ayrık olay ve ayrık olmayan olay üzerinde durulur.',
            'c) El Kindî ve Laplace\'ın çalışmalarına yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '10.1.2.2',
          subTopicName: 'Basit Olayların Olasılıkları',
          description: 'Olasılık kavramı ile ilgili uygulamalar yapar.',
          details: [
            'a) Eş olası olan ve olmayan olayların olasılıkları hesaplanır.',
            'b) Tümleyen, ayrık olay ve ayrık olmayan olay ile ilgili olasılıklar hesaplanır.',
            'c) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "fonksiyonlar",
      topicName: 'Fonksiyonlar',
      gradeLevel: 10,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 7,
      kazanimlar: [
        {
          code: '10.2.1.1',
          subTopicName: 'Fonksiyon Kavramı ve Gösterimi',
          description: 'Fonksiyonlarla ilgili problemler çözer.',
          details: [
            'a) Fonksiyon kavramı açıklanır.',
            'b) Sadece gerçek sayılar üzerinde tanımlanmış fonksiyonlar ele alınır.',
            'c) İçine fonksiyon, örten fonksiyon, bire bir fonksiyon, eşit fonksiyon, birim (özdeşlik) fonksiyon, sabit fonksiyon, doğrusal fonksiyon, tek fonksiyon, çift fonksiyon ve parçalı tanımlı fonksiyon açıklanır.',
            'ç) İki fonksiyonun eşitliği örneklerle açıklanır.',
            'd) f ve g fonksiyonları kullanılarak f + g, f - g, f.g, f/g işlemleri yapılır, ancak parçalı tanımlı fonksiyonlarda bu işlemlere girilmez.',
            'e) Gerçek hayat problemlerine ve tablo-grafik kullanımına yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '10.2.1.2',
          subTopicName: 'Fonksiyon Kavramı ve Gösterimi',
          description: 'Fonksiyonların grafiklerini çizer.',
          details: [
            'a) f(x) = ax + b şeklindeki fonksiyonların grafikleri ile ilgili uygulamalar yapılır.',
            'b) Parçalı tanımlı şekilde verilen fonksiyonların grafikleri çizilir.',
            'c) f(x) = ax + b tipindeki fonksiyonların grafiği bilgi ve iletişim teknolojileri yardımıyla çizilerek a ve b katsayıları ile fonksiyon grafiği arasındaki ilişki ele alınır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.2.1.3',
          subTopicName: 'Fonksiyon Kavramı ve Gösterimi',
          description: 'Fonksiyonların grafiklerini yorumlar.',
          details: [
            'a) Grafiği verilen fonksiyonların tanım ve görüntü kümeleri gösterilir.',
            'b) Bir fonksiyon grafiğinde, fonksiyonun x ekseni üzerinde tanımlı olduğu her bir noktadan y eksenine paralel çizilen doğruların, grafiği yalnızca bir noktada kestiğine (düşey/dikey doğru testi) işaret edilir.',
            'c) Bir f fonksiyonunun grafiğinin y = f(x) denkleminin grafiği olduğu ve grafiğin (varsa), x eksenini kestiği noktaların f(x) = 0 denkleminin gerçek sayılardaki çözüm kümesi olduğu vurgulanır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.2.1.4',
          subTopicName: 'Fonksiyon Kavramı ve Gösterimi',
          description: 'Gerçek hayat durumlarından doğrusal fonksiyonlarla ifade edilebilenlerin grafik gösterimlerini yapar.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '10.2.2.1',
          subTopicName: 'İki Fonksiyonun Bileşkesi ve Bir Fonksiyonun Tersi',
          description: 'Bire bir ve örten fonksiyonlar ile ilgili uygulamalar yapar.',
          details: [
            'a) Bir fonksiyonun bire bir ve örtenliği grafik üzerinde yatay doğru testiyle incelenir ve cebirsel olarak ilişkilendirilir.',
            'b) Bilgi ve iletişim teknolojileri yardımıyla bir fonksiyonun bire bir ve örten olup olmadığı belirlenir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '10.2.2.2',
          subTopicName: 'İki Fonksiyonun Bileşkesi ve Bir Fonksiyonun Tersi',
          description: 'Fonksiyonlarda bileşke işlemiyle ilgili işlemler yapar.',
          details: [
            'a) Bileşke işlemi, fonksiyonların cebirsel ve grafik gösterimleri ile ilişkilendirilerek ele alınır.',
            'b) Fonksiyonlarda bileşke işleminin birleşme özelliğinin olduğu belirtilir, değişme özelliğinin olmadığı örneklerle gösterilir.',
            'c) Parçalı tanımlı fonksiyonların bileşkesine girilmez.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.2.2.3',
          subTopicName: 'İki Fonksiyonun Bileşkesi ve Bir Fonksiyonun Tersi',
          description: 'Verilen bir fonksiyonun tersini bulur.',
          details: [
            'a) Bir fonksiyonun tersinin de fonksiyon olması için gerekli şartlar belirtilir.',
            'b) Sadece bire bir ve örten doğrusal fonksiyonun tersinin grafiği çizilir; fonksiyonun grafiği ile tersinin grafiğinin y=x doğrusuna göre simetrik olduğu gösterilir.',
            'c) Parçalı tanımlı fonksiyonların tersi verilmez.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "polinomlar",
      topicName: 'Polinomlar',
      gradeLevel: 10,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 8,
      kazanimlar: [
        {
          code: '10.3.1.1',
          subTopicName: 'Polinom Kavramı ve Polinomlarla İşlemler',
          description: 'Bir değişkenli polinom kavramını açıklar.',
          details: [
            'a) Polinomun derecesi, katsayıları ve sabit terimi belirtilir.',
            'b) Sabit polinom, sıfır polinomu ve iki polinomun eşitliği örneklerle açıklanır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '10.3.1.2',
          subTopicName: 'Polinom Kavramı ve Polinomlarla İşlemler',
          description: 'Polinomlarla toplama, çıkarma, çarpma ve bölme işlemlerini yapar.',
          details: [
            'a) Bir P(x) polinomunun x - a ile bölümünden kalan P(a) dır. P(a) = 0 ⇔ x - a, P(x) in bir çarpanı olduğu vurgulanır.',
            'b) Polinomun sıfırı kavramı bölme işlemiyle ilişkilendirilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.3.2.1',
          subTopicName: 'Polinomların Çarpanlara Ayrılması',
          description: 'Bir polinomu çarpanlarına ayırır.',
          details: [
            'a) Ortak çarpan parantezine alma ve değişken değiştirme yöntemleri kullanılarak çarpanlara ayırma uygulamaları yapılır.',
            'b) Tam kare, iki kare farkı, iki terimin toplamının ve farkının küpü, iki terimin küplerinin toplamı ve farkına ait özdeşlikler kullanılarak çarpanlara ayırma uygulamaları yapılır.',
            'c) ax² + bx + c biçimindeki ifadeler çarpanlarına ayrılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '10.3.2.2',
          subTopicName: 'Polinomların Çarpanlara Ayrılması',
          description: 'Rasyonel ifadelerin sadeleştirilmesi ile ilgili işlemler yapar.',
          details: [
            'a) Rasyonel ifade kavramı tanıtılır.',
            'b) Çarpanları polinom olmayan ifadelerde çarpanlara ayırma uygulamalarına yer verilmez.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "ikinci_derece_denklemler",
      topicName: 'İkinci Dereceden Denklemler',
      gradeLevel: 10,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 9,
      kazanimlar: [
        {
          code: '10.4.1.1',
          subTopicName: 'İkinci Dereceden Bir Bilinmeyenli Denklemler',
          description: 'İkinci dereceden bir bilinmeyenli denklem kavramını açıklar.',
          details: [
            'İkinci dereceden bir bilinmeyenli denklemlerin tarihsel gelişim sürecine ve bu süreçte rol alan Brahmagupta, Harezmi ve Abdulhamid İbn Türk\'ün çalışmalarına yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '10.4.1.2',
          subTopicName: 'İkinci Dereceden Bir Bilinmeyenli Denklemler',
          description: 'İkinci dereceden bir bilinmeyenli denklemleri çözer.',
          details: [
            'a) ax² + bx + c biçimindeki cebirsel ifadelerin; tam kare ve iki kare farkına ait özdeşlikler kullanılarak çarpanlara ayrılmasıyla ilgili uygulamalar yapılır.',
            'b) Denklemlerin çözümünde farklı yöntemlerden (çarpanlara ayırma, tam kareye tamamlama, değişken değiştirme, iki kare farkı, diskriminant) yararlanılır.',
            'c) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.4.1.3',
          subTopicName: 'İkinci Dereceden Bir Bilinmeyenli Denklemler',
          description: 'Bir karmaşık sayının a+ib (a,b ∈ ℝ) biçiminde ifade edildiğini açıklar.',
          details: [
            'a) Diskriminantın sıfırdan küçük olduğu durumlarda ikinci dereceden bir bilinmeyenli denklemlerin köklerinin bulunabilmesi için gerçek sayılar kümesini kapsayan yeni bir sayı kümesi tanımlama gereği örneklerle açıklanır.',
            'b) i² = -1 olmak üzere bir karmaşık sayı a + ib (a,b ∈ ℝ) biçiminde gösterilir.',
            'c) Köklerin birbirinin eşleniği olduğu belirtilir.',
            'ç) Karmaşık sayının eşleniği dışındaki özelliklere ve işlemlere girilmez.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '10.4.1.4',
          subTopicName: 'İkinci Dereceden Bir Bilinmeyenli Denklemler',
          description: 'İkinci dereceden bir bilinmeyenli denklemin kökleri ile katsayıları arasındaki ilişkileri kullanarak işlemler yapar.',
          details: [
            'a) Sadece kökler toplamı ve çarpımı ile denklemin katsayıları arasındaki ilişkiler üzerinde durulur.',
            'b) Kökleri verilen ikinci dereceden denklemi elde etme ile ilgili uygulamalara yer verilir.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "dortgenler_cokgenler",
      topicName: 'Dörtgenler ve Çokgenler',
      gradeLevel: 10,
      learningArea: 'GEOMETRİ',
      sortOrder: 10,
      kazanimlar: [
        {
          code: '10.5.1.1',
          subTopicName: 'Çokgenler',
          description: 'Çokgen kavramını açıklayarak işlemler yapar.',
          details: [
            'a) İçbükey çokgenlere girilmez.',
            'b) Düzgün çokgenler hatırlatılır, iç ve dış açılarının ölçüleri bulunur.',
            'c) Çokgenlerin köşegenleri ile ilgili özelliklere ve alan problemlerine yer verilmez.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '10.5.2.1',
          subTopicName: 'Dörtgenler ve Özellikleri',
          description: 'Dörtgenin temel elemanlarını ve özelliklerini açıklayarak problemler çözer.',
          details: [
            'a) Dışbükey ve içbükey dörtgen kavramları açıklanır. (Bundan sonra dörtgen denildiğinde dış bükey dörtgen anlaşılmalıdır.)',
            'b) Dörtgenin iç ve dış açılarının ölçüleri toplamı bulunur.',
            'c) Dörtgenin çevresi üzerinde durulur.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '10.5.3.1',
          subTopicName: 'Özel Dörtgenler',
          description: 'Özel dörtgenlerin açı, kenar, köşegen ve alan özelliklerini açıklayarak problemler çözer.',
          details: [
            'a) Yamuk, paralelkenar, eşkenar dörtgen, dikdörtgen, kare ve deltoid arasındaki hiyerarşik ilişkilere yer verilir.',
            'b) Hiyerarşik ilişkiye göre her bir özel dörtgen kendi içerisinde; açı, kenar, köşegen ve alan özellikleri bağlamında ele alınır.',
            'c) Origami, tangram kullanılarak uygulamalar yapılır.',
            'ç) Geleneksel mimaride kullanılan motif örneklerinde yer alan çokgen örneklerine yer verilir.',
            'd) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "uzay_geometri_10",
      topicName: 'Uzay Geometri (Prizma ve Piramit)',
      gradeLevel: 10,
      learningArea: 'GEOMETRİ',
      sortOrder: 11,
      kazanimlar: [
        {
          code: '10.6.1.1',
          subTopicName: 'Katı Cisimler',
          description: 'Dik prizmalar ve dik piramitlerin uzunluk, alan ve hacim bağıntılarını oluşturur.',
          details: [
            'a) Üçgen, dörtgen ve altıgen dik prizma/piramit ile sınırlandırılır.',
            'b) Gerçek hayat problemlerine yer verilir.',
            'c) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "trigonometri",
      topicName: 'Trigonometri',
      gradeLevel: 11,
      learningArea: 'GEOMETRİ',
      sortOrder: 12,
      kazanimlar: [
        {
          code: '11.1.1.1',
          subTopicName: 'Yönlü Açılar',
          description: 'Yönlü açıyı açıklar.',
          details: [],
          isKeyKazanim: true,
        },
        {
          code: '11.1.1.2',
          subTopicName: 'Yönlü Açılar',
          description: 'Açı ölçü birimlerini açıklayarak birbiri ile ilişkilendirir.',
          details: [
            'a) Derecenin alt birimleri olan dakika ve saniyeden bahsedilir.',
            'b) Derece ile radyan ilişkilendirilir, grada girilmez.',
            'c) Açının esas ölçüsü bulunur.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '11.1.2.1',
          subTopicName: 'Trigonometrik Fonksiyonlar',
          description: 'Trigonometrik fonksiyonları birim çember yardımıyla açıklar.',
          details: [
            'a) Trigonometrik fonksiyonlar arasındaki temel özdeşlikler, oluşturulan benzer üçgenler yardımıyla incelenir.',
            'b) Trigonometrik fonksiyonların bölgelere göre işaretleri incelenir.',
            'c) Trigonometrik fonksiyonların açı değerlerine göre sıralanmasına yer verilir.',
            'ç) k ∈ ℤ⁺ olmak üzere kπ/2 ± θ açılarının trigonometrik değerleri θ dar açısının trigonometrik değerlerinden yararlanarak hesaplanır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '11.1.2.2',
          subTopicName: 'Trigonometrik Fonksiyonlar',
          description: 'Kosinüs teoremiyle ilgili problemler çözer.',
          details: [
            'a) Kosinüs teoremi, Pisagor teoreminden yararlanılarak elde edilir.',
            'b) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '11.1.2.3',
          subTopicName: 'Trigonometrik Fonksiyonlar',
          description: 'Sinüs teoremiyle ilgili problemler çözer.',
          details: [
            'a) Sinüs teoremi, iki kenarının uzunluğu ve bu kenarlar arasındaki açının ölçüsü verilen üçgenin alanından yararlanılarak elde edilir.',
            'b) Sinüs teoremi çevrel çemberle ilişkilendirilmez.',
            'c) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '11.1.2.4',
          subTopicName: 'Trigonometrik Fonksiyonlar',
          description: 'Trigonometrik fonksiyon grafiklerini çizer.',
          details: [
            'a) y=sinx ve y=cosx fonksiyonları dışındaki fonksiyonların grafik çizimlerinde sadece bilgi ve iletişim teknolojileri kullanılır.',
            'b) Periyodik fonksiyon tanımı verilir, trigonometrik fonksiyonların periyodik oldukları gösterilir.',
            'c) f(x) = a.sin(bx + c) + k türündeki fonksiyonların grafikleri ve katsayılarının grafik üzerindeki etkileri ele alınır.',
            'ç) Grafikleri yardımıyla trigonometrik fonksiyonların tek ya da çift fonksiyon olup olmadıkları belirlenir.',
            'd) Sekant ve kosekant fonksiyonlarının grafiklerine yer verilmez.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '11.1.2.5',
          subTopicName: 'Trigonometrik Fonksiyonlar',
          description: 'Sinüs, kosinüs, tanjant fonksiyonlarının ters fonksiyonlarını açıklar.',
          details: [
            'Ters trigonometrik fonksiyonların grafiklerine yer verilmez.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "analitik_geometri",
      topicName: 'Analitik Geometri - Doğru Denklemleri',
      gradeLevel: 11,
      learningArea: 'GEOMETRİ',
      sortOrder: 13,
      kazanimlar: [
        {
          code: '11.2.1.1',
          subTopicName: 'Doğrunun Analitik İncelenmesi',
          description: 'Analitik düzlemde iki nokta arasındaki uzaklığı veren bağıntıyı elde ederek problemler çözer.',
          details: [],
          isKeyKazanim: true,
        },
        {
          code: '11.2.1.2',
          subTopicName: 'Doğrunun Analitik İncelenmesi',
          description: 'Bir doğru parçasını belli bir oranda (içten veya dıştan) bölen noktanın koordinatlarını hesaplar.',
          details: [
            'a) Bir doğru parçasının orta noktasının koordinatları buldurulur.',
            'b) Bir üçgenin ağırlık merkezinin koordinatları buldurulur.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '11.2.1.3',
          subTopicName: 'Doğrunun Analitik İncelenmesi',
          description: 'Analitik düzlemde doğruları inceleyerek işlemler yapar.',
          details: [
            'a) Bir doğrunun eğim açısı ve eğimi tanımlanır.',
            'b) Analitik düzlemde bir doğrunun denklemi oluşturulur.',
            'c) Eksenlere paralel ve orijinden geçen doğruların denklemleri bulunur ve bulunan denklemlerin grafikleri yorumlanır.',
            'ç) İki doğrunun birbirine göre durumları incelenir ve kesişen iki doğrunun kesişim noktası bulunur.',
            'd) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '11.2.1.4',
          subTopicName: 'Doğrunun Analitik İncelenmesi',
          description: 'Bir noktanın bir doğruya uzaklığını hesaplar.',
          details: [
            'Bir noktanın bir doğruya uzaklığı ve paralel iki doğru arasındaki uzaklık ile ilgili uygulamalar yapılır.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "fonksiyonlarda_uygulamalar",
      topicName: 'Fonksiyonlarda Uygulamalar',
      gradeLevel: 11,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 14,
      kazanimlar: [
        {
          code: '11.3.1.1',
          subTopicName: 'Fonksiyonlarla İlgili Uygulamalar',
          description: 'Fonksiyonun grafik ve tablo temsilini kullanarak problem çözer.',
          details: [
            'a) Grafiğin x ve y eksenlerini kestiği noktalar; fonksiyonun pozitif, negatif, artan ve azalan olduğu aralıklar; fonksiyonun maksimum ve minimum değerleri ve bunların (verilen durum bağlamında) anlamları grafik üzerinden açıklanır.',
            'b) Cebirsel ifade, grafik veya tablo ile verilen fonksiyonun belli bir aralıktaki ortalama değişim hızı (kesenin eğimi, (f(b)-f(a))/(b-a)) hesaplanır.',
            'c) Fonksiyonun grafiği bilgi ve iletişim teknolojileri yardımıyla çizilir ve yorumlanır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '11.3.2.1',
          subTopicName: 'İkinci Dereceden Fonksiyonlar ve Grafikleri',
          description: 'İkinci dereceden bir değişkenli fonksiyonun grafiğini çizerek yorumlar.',
          details: [
            'a) Fonksiyonun grafiğinin tepe noktası, eksenleri kestiği noktalar ve simetri ekseni buldurulur.',
            'b) Fonksiyonun grafiğinin tepe noktası ile fonksiyonun en küçük ya da en büyük değeri ilişkilendirilir.',
            'c) Fonksiyonun katsayılarındaki değişimin, fonksiyonun grafiği üzerine etkisi bilgi ve iletişim teknolojilerinden yararlanılarak yorumlanır.',
            'ç) Biri tepe noktası olmak üzere iki noktası verilen veya biri y ekseni üzerinde olmak üzere üç noktası verilen ikinci dereceden fonksiyon oluşturulur.',
            'd) Bir doğru ile bir parabolün birbirine göre durumları incelenir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '11.3.2.2',
          subTopicName: 'İkinci Dereceden Fonksiyonlar ve Grafikleri',
          description: 'İkinci dereceden fonksiyonlarla modellenebilen problemleri çözer.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '11.3.3.1',
          subTopicName: 'Fonksiyonların Dönüşümleri',
          description: 'Bir fonksiyonun grafiğinden, dönüşümler yardımı ile yeni fonksiyon grafikleri çizer.',
          details: [
            'a) Tek ve çift fonksiyonların grafiğinin simetri özellikleri üzerinde durulur.',
            'b) y = f(x) + b, y = f(x - a), y = k f(x), y = f(kx), y = -f(x), y = f(-x) dönüşümlerinin grafikleri bilgi ve iletişim teknolojilerinden yararlanılarak verilir.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "denklem_esitsizlik_sistemleri",
      topicName: 'Denklem ve Eşitsizlik Sistemleri',
      gradeLevel: 11,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 15,
      kazanimlar: [
        {
          code: '11.4.1.1',
          subTopicName: 'İkinci Dereceden İki Bilinmeyenli Denklem Sistemleri',
          description: 'İkinci dereceden iki bilinmeyenli denklem sistemlerinin çözüm kümesini bulur.',
          details: [
            'Bilgi ve iletişim teknolojilerinden yararlanılarak çizilen grafikler yardımıyla çözüm yorumlatılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '11.4.2.1',
          subTopicName: 'İkinci Dereceden Bir Bilinmeyenli Eşitsizlikler ve Eşitsizlik Sistemleri',
          description: 'İkinci dereceden bir bilinmeyenli eşitsizliklerin çözüm kümesini bulur.',
          details: [
            'a) ax + b veya ax² + bx + c şeklindeki ifadelerin çarpımı veya bölümü biçiminde verilen eşitsizliklerin çözüm kümesi buldurulur.',
            'b) Bilgi ve iletişim teknolojilerinden yararlanılarak çizilen grafikler yardımıyla çözüm yorumlatılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '11.4.2.2',
          subTopicName: 'İkinci Dereceden Bir Bilinmeyenli Eşitsizlikler ve Eşitsizlik Sistemleri',
          description: 'İkinci dereceden bir bilinmeyenli eşitsizlik sistemlerinin çözüm kümesini bulur.',
          details: [],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "cember_daire",
      topicName: 'Çember ve Daire',
      gradeLevel: 11,
      learningArea: 'GEOMETRİ',
      sortOrder: 16,
      kazanimlar: [
        {
          code: '11.5.1.1',
          subTopicName: 'Çemberin Temel Elemanları',
          description: 'Çemberde teğet, kiriş, çap, yay ve kesen kavramlarını açıklar.',
          details: [
            'Bir çember ile bir doğrunun birbirlerine göre durumları ele alınır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '11.5.1.2',
          subTopicName: 'Çemberin Temel Elemanları',
          description: 'Çemberde kirişin özelliklerini göstererek işlemler yapar.',
          details: [
            'a) Bir çemberde, kirişin orta dikmesinin çemberin merkezinden geçtiği ve bir kirişin orta noktasını çemberin merkezine birleştiren doğrunun da kirişe dik olduğu gösterilir.',
            'b) Bir çemberde kirişlerin uzunlukları ile merkeze olan uzaklıkları arasındaki ilişki üzerinde durulur.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '11.5.2.1',
          subTopicName: 'Çemberde Açılar',
          description: 'Bir çemberde merkez, çevre, iç, dış ve teğet-kiriş açıların özelliklerini kullanarak işlemler yapar.',
          details: [
            'a) Üçgenin çevrel çemberi çizdirilir.',
            'b) Sinüs teoreminin çevrel çemberin yarıçapı ile ilişkisi üzerinde durulur.',
            'c) Pergel-cetvelden veya bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '11.5.3.1',
          subTopicName: 'Çemberde Teğet',
          description: 'Çemberde teğetin özelliklerini göstererek işlemler yapar.',
          details: [
            'a) Çemberin dışındaki bir noktadan çizilen teğet parçalarının uzunluklarının eşit olduğu gösterilir.',
            'b) Üçgenin iç teğet ve dış teğet çemberleri çizilir.',
            'c) İki çemberin ortak teğetine girilmez.',
            'ç) Bilgi ve iletişim teknolojileri yardımıyla bir çember ve bu çembere dışındaki bir noktadan iki teğet çizilerek dışarıda alınan noktanın sürüklenmesi suretiyle ortaya çıkan durum ele alınır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '11.5.4.1',
          subTopicName: 'Dairenin Çevresi ve Alanı',
          description: 'Dairenin çevre ve alan bağıntılarını oluşturur.',
          details: [
            'a) Dairenin çevresi ve alanı ile ilgili uygulamalar yapılır.',
            'b) Daire diliminin alanı ve yay uzunluğu bağıntıları buldurularak uygulamalar yapılır.',
            'c) Archimedes\'in çalışmalarına yer verilir.',
            'ç) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "uzay_geometri_11",
      topicName: 'Uzay Geometri (Silindir, Koni, Küre)',
      gradeLevel: 11,
      learningArea: 'GEOMETRİ',
      sortOrder: 17,
      kazanimlar: [
        {
          code: '11.6.1.1',
          subTopicName: 'Katı Cisimler',
          description: 'Küre, dik dairesel silindir ve dik dairesel koninin alan ve hacim bağıntılarını oluşturarak işlemler yapar.',
          details: [
            'a) Gerçek hayat problemlerine yer verilir.',
            'b) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "olasilik",
      topicName: 'Olasılık',
      gradeLevel: 11,
      learningArea: 'VERİ, SAYMA VE OLASILIK',
      sortOrder: 18,
      kazanimlar: [
        {
          code: '11.7.1.1',
          subTopicName: 'Koşullu Olasılık',
          description: 'Koşullu olasılığı açıklayarak problemler çözer.',
          details: [
            'a) Olasılık konusunun tarihsel gelişim sürecinden bahsedilir.',
            'b) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '11.7.1.2',
          subTopicName: 'Koşullu Olasılık',
          description: 'Bağımlı ve bağımsız olayları açıklayarak gerçekleşme olasılıklarını hesaplar.',
          details: [
            'Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '11.7.1.3',
          subTopicName: 'Koşullu Olasılık',
          description: 'Bileşik olayı açıklayarak gerçekleşme olasılığını hesaplar.',
          details: [
            'a) Ağaç şemasından yararlanılır.',
            'b) En fazla üç aşamalı olaylardan seçim yapılır.',
            'c) "ve, veya" bağlaçları ile oluşturulan olayların olasılıkları hesaplatılır.',
            'ç) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '11.7.2.1',
          subTopicName: 'Deneysel ve Teorik Olasılık',
          description: 'Deneysel olasılık ile teorik olasılığı ilişkilendirir.',
          details: [
            'Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "ustel_logaritmik_fonksiyonlar",
      topicName: 'Üstel ve Logaritmik Fonksiyonlar',
      gradeLevel: 12,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 19,
      kazanimlar: [
        {
          code: '12.1.1.1',
          subTopicName: 'Üstel Fonksiyon',
          description: 'Üstel fonksiyonu açıklar.',
          details: [
            'a) Üstel fonksiyonlara neden ihtiyaç duyulduğu vurgulanmalıdır.',
            'b) Üslü ifadeler ve bunlarla yapılan işlemlerin özellikleri hatırlatılır.',
            'c) Üstel fonksiyonların bire bir ve örten olduğu grafik yardımıyla gösterilir.',
            'ç) a nın aldığı değerlere göre f(x) = aˣ fonksiyonunun grafiğinin değişimini incelemek için bilgi ve iletişim teknolojilerinden de yararlanılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.1.2.1',
          subTopicName: 'Logaritma Fonksiyonu',
          description: 'Logaritma fonksiyonu ile üstel fonksiyonu ilişkilendirerek problemler çözer.',
          details: [
            'a) a ∈ ℝ⁺ - {1} olmak üzere logaritma fonksiyonunun grafiği üstel fonksiyonun grafiğinden yararlanarak çizilir. y = aˣ ve y = log_a x fonksiyonlarının grafiklerinin y=x doğrusuna göre simetrik olduğu belirtilir.',
            'b) a ∈ ℝ⁺ - {1} olmak üzere f: ℝ⁺ → ℝ, f(x) = log_a x logaritma fonksiyonunun a > 1 için artan fonksiyon, 0 < a < 1 için azalan fonksiyon olduğu verilir. a nın aldığı değerlere göre logaritma fonksiyonunun grafiğinin değişimini incelemek için bilgi ve iletişim teknolojilerinden yararlanılır.',
            'c) Gelenbevi İsmail Efendi ve John Napier\'in çalışmalarına yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.1.2.2',
          subTopicName: 'Logaritma Fonksiyonu',
          description: '10 ve e tabanında logaritma fonksiyonunu tanımlayarak problemler çözer.',
          details: [
            'e sayısının irrasyonel olduğu vurgulanarak matematikte ve diğer bilim dallarında kullanımından bahsedilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '12.1.2.3',
          subTopicName: 'Logaritma Fonksiyonu',
          description: 'Logaritma fonksiyonunun özelliklerini kullanarak işlemler yapar.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '12.1.3.1',
          subTopicName: 'Üstel, Logaritmik Denklemler ve Eşitsizlikler',
          description: 'Üstel, logaritmik denklemlerin ve eşitsizliklerin çözüm kümelerini bulur.',
          details: [],
          isKeyKazanim: true,
        },
        {
          code: '12.1.3.2',
          subTopicName: 'Üstel, Logaritmik Denklemler ve Eşitsizlikler',
          description: 'Üstel ve logaritmik fonksiyonları gerçek hayat durumlarını modellemede kullanır.',
          details: [
            'a) Gerçek hayat durumlarından nüfus artışı, bakteri popülasyonu, radyoaktif maddelerin bozunumu (yarı ömür), fosil yaşlarının tayini, deprem şiddeti (Richter ölçeği), pH değeri, ses şiddeti (desibel) gibi örneklere yer verilir.',
            'b) İsraf ve tasarruf kavramları hakkında farkındalık oluşturacak örneklere yer verilir.',
            'c) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "diziler",
      topicName: 'Diziler',
      gradeLevel: 12,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 20,
      kazanimlar: [
        {
          code: '12.2.1.1',
          subTopicName: 'Gerçek Sayı Dizileri',
          description: 'Dizi kavramını fonksiyon kavramıyla ilişkilendirerek açıklar.',
          details: [
            'Sonlu dizi, sabit dizi ve dizilerin eşitliği verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.2.1.2',
          subTopicName: 'Gerçek Sayı Dizileri',
          description: 'Genel terimi veya indirgeme bağıntısı verilen bir sayı dizisinin terimlerini bulur.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '12.2.1.3',
          subTopicName: 'Gerçek Sayı Dizileri',
          description: 'Aritmetik ve geometrik dizilerin özelliklerini kullanarak işlemler yapar.',
          details: [
            'a) İlk n terim toplamı bulunur.',
            'b) Toplam sembolü tanıtılır ancak özellikleri verilmez.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '12.2.1.4',
          subTopicName: 'Gerçek Sayı Dizileri',
          description: 'Diziler yardımıyla gerçek hayat durumları ile ilgili problemler çözer.',
          details: [
            'Aritmetik, geometrik ve Fibonacci dizilerine doğadan, çeşitli sanat dallarından örnekler verilir.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "trigonometri_12",
      topicName: 'Trigonometri',
      gradeLevel: 12,
      learningArea: 'GEOMETRİ',
      sortOrder: 21,
      kazanimlar: [
        {
          code: '12.3.1.1',
          subTopicName: 'Toplam-Fark ve İki kat Açı Formülleri',
          description: 'İki açının ölçüleri toplamının ve farkının trigonometrik değerlerine ait formülleri oluşturarak işlemler yapar.',
          details: [
            'Dönüşüm ve ters dönüşüm formülleri verilmez.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.3.1.2',
          subTopicName: 'Toplam-Fark ve İki kat Açı Formülleri',
          description: 'İki kat açı formüllerini oluşturarak işlemler yapar.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '12.3.2.1',
          subTopicName: 'Trigonometrik Denklemler',
          description: 'Trigonometrik denklemlerin çözüm kümelerini bulur.',
          details: [
            'a) a, b, c ∈ ℝ olmak üzere a sin f(x) + b cos g(x) = c biçimindeki trigonometrik denklemlerin kökleri buldurulur; a, b ve c katsayıları ile çözüm ilişkilendirilir.',
            'b) Gerçek hayat problemlerine yer verilir.',
            'c) El Battani\'nin çalışmalarına yer verilir.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "donusumler",
      topicName: 'Dönüşümler',
      gradeLevel: 12,
      learningArea: 'GEOMETRİ',
      sortOrder: 22,
      kazanimlar: [
        {
          code: '12.4.1.1',
          subTopicName: 'Analitik Düzlemde Temel Dönüşümler',
          description: 'Analitik düzlemde koordinatları verilen bir noktanın öteleme, dönme ve simetri dönüşümleri altındaki görüntüsünün koordinatlarını bulur.',
          details: [
            'a) Öteleme, simetri ve dönme kavramları hatırlatılır.',
            'b) Noktanın; noktaya, eksenlere, y=x doğrusuna, bir doğruya göre simetrileri ve doğrunun noktaya göre simetrileri vurgulanır. Doğrunun doğruya göre simetrilerine yer verilmez.',
            'c) Bilgi ve iletişim teknolojileri yardımıyla öteleme, simetri ve dönme ele alınır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.4.1.2',
          subTopicName: 'Analitik Düzlemde Temel Dönüşümler',
          description: 'Temel dönüşümler ve bileşkeleriyle ilgili problem çözer.',
          details: [
            'a) Modelleme çalışmalarına yer verilir.',
            'b) Doğadan ve mimari eserlerden örneklendirme yapılır.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "turev",
      topicName: 'Türev',
      gradeLevel: 12,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 23,
      kazanimlar: [
        {
          code: '12.5.1.1',
          subTopicName: 'Limit ve Süreklilik',
          description: 'Bir fonksiyonun bir noktadaki limiti, soldan limit ve sağdan limit kavramlarını açıklar.',
          details: [
            'a) Limit kavramı bir bağımsız değişkenin verilen bir sayıya yaklaşmasından hareketle, tablo ve grafikler yardımıyla açıklanır.',
            'b) Bilgi ve iletişim teknolojilerinden yararlanılır.',
            'c) Cauchy\'nin çalışmalarına yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.5.1.2',
          subTopicName: 'Limit ve Süreklilik',
          description: 'Limit ile ilgili özellikleri belirterek uygulamalar yapar.',
          details: [
            'a) Polinom, köklü, üstel, logaritmik ve trigonometrik fonksiyonlar içeren limit uygulamaları yapılır ancak sonucu ± ∞ olan limit durumlarına girilmez.',
            'b) Sadece pay ve paydası çarpanlarına ayrılarak belirsizliğin kaldırılabileceği limit örneklerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '12.5.1.3',
          subTopicName: 'Limit ve Süreklilik',
          description: 'Bir fonksiyonun bir noktadaki sürekliliğini açıklar.',
          details: [
            'a) Fonksiyonun grafiği üzerinde sürekli ve süreksiz olduğu noktalar buldurulur.',
            'b) Limitin tarihsel gelişiminden ve Salih Zeki\'nin bu alana katkılarından bahsedilir.',
            'c) Bilgi ve iletişim teknolojileri yardımıyla süreklilik uygulamaları yaptırılır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '12.5.2.1',
          subTopicName: 'Anlık Değişim Oranı ve Türev',
          description: 'Türev kavramını açıklayarak işlemler yapar.',
          details: [
            'a) Anlık değişim oranı fizik ve geometri modellerinden yararlanılarak açıklanır.',
            'b) Verilen bir fonksiyonun bir noktadaki türev değeri ile o noktadaki teğetinin eğimi arasındaki ilişki üzerinde durulur.',
            'c) Bir fonksiyonun bir noktadaki soldan türevi ve sağdan türevi ile türev arasındaki ilişki açıklanır.',
            'ç) f(x) = c, f(x) = axⁿ (a, c ∈ ℝ, n ∈ ℚ) şeklindeki fonksiyonlar için türev kuralları verilir. Bunun dışındaki fonksiyonların (kapalı ve parametrik fonksiyonlar dâhil) türev kurallarına yer verilmez.',
            'd) Rolle\'nin çalışmalarına yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.5.2.2',
          subTopicName: 'Anlık Değişim Oranı ve Türev',
          description: 'Bir fonksiyonun bir noktada ve bir aralıkta türevlenebilirliğini değerlendirir.',
          details: [
            'a) Bir fonksiyonun bir noktada türevli olması için gerek ve yeter şartları inceler.',
            'b) Fonksiyonun türevli olmadığı noktalarla grafiği arasında ilişki kurulur.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '12.5.2.3',
          subTopicName: 'Anlık Değişim Oranı ve Türev',
          description: 'Türevlenebilen iki fonksiyonun toplamı, farkı, çarpımı ve bölümünün türevine ait kurallar yardımıyla işlemler yapar.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '12.5.2.4',
          subTopicName: 'Anlık Değişim Oranı ve Türev',
          description: 'İki fonksiyonun bileşkesinin türevine ait kuralı (zincir kuralı) oluşturularak türev hesabı yapar.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '12.5.3.1',
          subTopicName: 'Türevin Uygulamaları',
          description: 'Bir fonksiyonun artan veya azalan olduğu aralıkları türev yardımıyla belirler.',
          details: [],
          isKeyKazanim: true,
        },
        {
          code: '12.5.3.2',
          subTopicName: 'Türevin Uygulamaları',
          description: 'Bir fonksiyonun mutlak maksimum ve mutlak minimum, yerel maksimum, yerel minimum noktalarını belirler.',
          details: [
            'Bilgi ve iletişim teknolojilerinden yararlanılarak grafik çizimine yer verilir ve yorumlanır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '12.5.3.3',
          subTopicName: 'Türevin Uygulamaları',
          description: 'Türevi yardımıyla bir fonksiyonun grafiğini çizer.',
          details: [
            'a) Grafik çizimleri polinom fonksiyonlarla sınırlandırılır.',
            'b) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '12.5.3.4',
          subTopicName: 'Türevin Uygulamaları',
          description: 'Maksimum ve minimum problemlerini türev yardımıyla çözer.',
          details: [
            'Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "integral",
      topicName: 'İntegral',
      gradeLevel: 12,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 24,
      kazanimlar: [
        {
          code: '12.6.1.1',
          subTopicName: 'Belirsiz İntegral',
          description: 'Bir fonksiyonun belirsiz integralini açıklayarak integral alma kurallarını oluşturur.',
          details: [
            'a) Belirsiz integral alma kuralları n ≠ -1 olmak üzere f(x) = axⁿ (a, c ∈ ℝ, n ∈ ℚ) şeklindeki fonksiyonlarla sınırlandırılır.',
            'b) Bir fonksiyonun bir sabitle çarpımının, iki fonksiyonun toplamının ve farkının integral alma kuralları verilerek uygulamalar yaptırılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.6.1.2',
          subTopicName: 'Belirsiz İntegral',
          description: 'Değişken değiştirme yoluyla integral alma işlemleri yapar.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '12.6.2.1',
          subTopicName: 'Belirli İntegral ve Uygulamaları',
          description: 'Bir fonksiyonun grafiği ile x ekseni arasında kalan sınırlı bölgenin alanını Riemann toplamı yardımıyla yaklaşık olarak hesaplar.',
          details: [
            'a) Gerçek hayatta karşılaşılan ve değeri alan formülleriyle hesaplanamayan alanların, uygun toplamların limiti olarak ifade edilebileceği açıklanır.',
            'b) Polinom fonksiyonlarla sınırlandırılır.',
            'c) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.6.2.2',
          subTopicName: 'Belirli İntegral ve Uygulamaları',
          description: 'Bir fonksiyonun belirli ve belirsiz integralleri arasındaki ilişkiyi açıklayarak işlemler yapar.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: '12.6.2.3',
          subTopicName: 'Belirli İntegral ve Uygulamaları',
          description: 'Belirli integralin özelliklerini kullanarak işlemler yapar.',
          details: [
            'Parçalı fonksiyonların belirli integraline yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: '12.6.2.4',
          subTopicName: 'Belirli İntegral ve Uygulamaları',
          description: 'Belirli integral ile alan hesabı yapar.',
          details: [
            'a) İki fonksiyonun grafikleri arasında kalan sınırlı bölgenin alanı hesaplanır.',
            'b) Gerçek hayat problemlerine yer verilir.',
            'c) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "AYT",
      subject: "Matematik",
      topicKey: "analitik_geometri_cember",
      topicName: 'Analitik Geometri - Çember',
      gradeLevel: 12,
      learningArea: 'GEOMETRİ',
      sortOrder: 25,
      kazanimlar: [
        {
          code: '12.7.1.1',
          subTopicName: 'Çemberin Analitik İncelenmesi',
          description: 'Merkezi ve yarıçapı verilen çemberin denklemini oluşturur.',
          details: [
            'a) M(a, b) merkezli ve r yarıçaplı çemberin standart denklemi (x-a)² + (y-b)² = r² yardımıyla çemberin genel denklemi x² + y² + Dx + Ey + F = 0 şeklinde elde edilir.',
            'b) Ax² + By² + Dx + Ey + F = 0 denkleminin hangi durumlarda çember oluşturduğu gösterilir.',
            'c) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: '12.7.1.2',
          subTopicName: 'Çemberin Analitik İncelenmesi',
          description: 'Denklemleri verilen doğru ile çemberin birbirine göre durumlarını belirleyerek işlemler yapar.',
          details: [
            'a) Doğru ile çemberin varsa kesişim noktaları bulunur.',
            'b) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "td_sayilar",
      topicName: 'Sayılar (Temel Düzey)',
      gradeLevel: 11,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 26,
      kazanimlar: [
        {
          code: 'TD.11.1.1.1',
          subTopicName: 'Sayı Kümeleri',
          description: 'Sayı kümelerini birbiriyle ilişkilendirir.',
          details: [],
          isKeyKazanim: true,
        },
        {
          code: 'TD.11.1.1.2',
          subTopicName: 'Sayı Kümeleri',
          description: 'Doğal sayıların çözümlenmesi ile ilgili problemler çözer.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: 'TD.11.1.1.3',
          subTopicName: 'Sayı Kümeleri',
          description: 'Eşit miktarda artarak devam eden sınırlı sayıdaki doğal sayıların toplamını bulur.',
          details: [],
          isKeyKazanim: false,
        },
        {
          code: 'TD.11.1.2.1',
          subTopicName: 'Bölünebilme',
          description: 'Tam sayılarda bölünebilme kurallarıyla ilgili işlemler yapar.',
          details: [
            '2, 3, 4, 5, 8, 9, 10, 11 ile bu sayılardan elde edilen 6, 12, 15 vb. sayıların bölünebilme kuralları verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: 'TD.11.1.2.2',
          subTopicName: 'Bölünebilme',
          description: 'Bir tamsayının pozitif tamsayı bölenlerinin sayısını bulur.',
          details: [
            'Asal sayılar ve asal çarpanlara ayırma vurgulanır.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "td_ucgenler",
      topicName: 'Üçgenler (Temel Düzey)',
      gradeLevel: 11,
      learningArea: 'GEOMETRİ',
      sortOrder: 27,
      kazanimlar: [
        {
          code: 'TD.11.2.1.1',
          subTopicName: 'Dik Üçgen',
          description: 'Dik üçgenlerle ilgili problemler çözer.',
          details: [
            'Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: 'TD.11.2.1.2',
          subTopicName: 'Dik Üçgen',
          description: 'Dik üçgende trigonometrik oranlarla ilgili problemler çözer.',
          details: [
            'Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: 'TD.11.2.1.3',
          subTopicName: 'Dik Üçgen',
          description: 'Üçgenlerin benzerliğiyle ilgili problemler çözer.',
          details: [
            'Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "td_denklem_esitsizlikler",
      topicName: 'Denklem ve Eşitsizlikler (Temel Düzey)',
      gradeLevel: 11,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 28,
      kazanimlar: [
        {
          code: 'TD.11.3.1.1',
          subTopicName: 'Birinci Dereceden Denklem ve Eşitsizlikler',
          description: 'Birinci dereceden bir veya iki bilinmeyenli denklemlerle ilgili problemler çözer.',
          details: [
            'Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: 'TD.11.3.1.2',
          subTopicName: 'Birinci Dereceden Denklem ve Eşitsizlikler',
          description: 'Birinci dereceden bir bilinmeyenli eşitsizliklerle ilgili problemler çözer.',
          details: [
            'Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: false,
        },
        {
          code: 'TD.11.3.2.1',
          subTopicName: 'Bilinçli Tüketici Aritmetiği',
          description: 'Gelir-giderleri göz önüne alarak birey, aile ve kurum bütçesi oluşturur.',
          details: [
            'Gelirler ve giderler dikkate alınarak birey, aile, kurum veya bir projenin bütçesi yapılır.',
          ],
          isKeyKazanim: true,
        },
        {
          code: 'TD.11.3.2.2',
          subTopicName: 'Bilinçli Tüketici Aritmetiği',
          description: 'Seyahatlerde mümkün olan alternatifleri karşılaştırır.',
          details: [
            'a) Seyahatin yaklaşık maliyet analizi yaptırılır.',
            'b) Gidilecek yere ilişkin bir zaman çizelgesi yaptırılır.',
          ],
          isKeyKazanim: false,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "td_cember_daire",
      topicName: 'Çember ve Daire (Temel Düzey)',
      gradeLevel: 11,
      learningArea: 'GEOMETRİ',
      sortOrder: 29,
      kazanimlar: [
        {
          code: 'TD.11.4.1.1',
          subTopicName: 'Çemberin Temel Elemanları',
          description: 'Çemberin temel elemanlarını tanır.',
          details: [
            'Çap, yay, teğet, kiriş, kavramları verilir ancak bu kavramların özelliklerine girilmez.',
          ],
          isKeyKazanim: true,
        },
        {
          code: 'TD.11.4.2.1',
          subTopicName: 'Çemberde Açılar',
          description: 'Çemberlerde açıların özelliklerini kullanarak işlemler yapar.',
          details: [
            'Sadece merkez ve çevre açı verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: 'TD.11.4.3.1',
          subTopicName: 'Dairenin Çevresi ve Alanı',
          description: 'Dairenin çevre ve alan bağıntılarını oluşturur.',
          details: [
            'a) Dairenin çevresi ve alanı ile ilgili işlemler yapar.',
            'b) Daire diliminin alanı ve yay uzunluğu bağıntıları verilir.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "td_denklem_esitsizlikler_12",
      topicName: 'Denklem ve Eşitsizlikler (Temel Düzey)',
      gradeLevel: 12,
      learningArea: 'SAYILAR VE CEBİR',
      sortOrder: 30,
      kazanimlar: [
        {
          code: 'TD.12.1.1.1',
          subTopicName: 'Üslü ve Köklü İfadeler',
          description: 'Üslü ve köklü ifadeler içeren denklemler çözer.',
          details: [
            'a) Üslü ve köklü ifadelerin özellikleri hatırlatılır.',
            'b) Gerçek hayat problemlerine yer verilir.',
          ],
          isKeyKazanim: true,
        },
        {
          code: 'TD.12.1.2.1',
          subTopicName: 'Bilinçli Tüketici Aritmetiği',
          description: 'Yüzde, oran ve orantı kavramlarıyla ilgili problemler çözer.',
          details: [
            'a) Yüzde hesaplamalarında aşağıda verilen bağlamlardan yararlanılabilir: Zamanında ödemeleri yapılmadığında gecikme bedeli ödenmesi gereken durumlar, Bir malın alış fiyatı üzerine KDV, ÖTV ve kâr eklenmesi; belli bir satış fiyatı üzerinden indirim yapılması gibi gerçek hayat durumları, Vade farkı, enflasyon gibi bireyin günlük yaşantısında sıklıkla karşılaştığı kavramlar, Yatırımların getirilerine yönelik veriler toplatılması ve yatırımlar içerisinde en iyi olanın belirlenmesi.',
            'b) Oran ve orantı kavramlarını içeren problemler oluştururken aşağıda verilen bağlamlardan yararlanılabilir: Farklı ürünlerin birim fiyatlarını karşılaştırma, Farklı para birimlerini birbirine çevirme, Farklı sayıda kişiler için hazırlanacak yemek için, kullanılması gereken malzeme miktarı, Araç kullanımı ile yakıt tüketimi arasındaki ilişkileri inceleme, Dakikaya/pakete bağlı telefon ücretleri gibi durumlar.',
            'c) Tutumlu olma hakkında farkındalık oluşturacak örneklere yer verilir.',
            'ç) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "td_veri",
      topicName: 'Veri (Temel Düzey)',
      gradeLevel: 12,
      learningArea: 'VERİ, SAYMA VE OLASILIK',
      sortOrder: 31,
      kazanimlar: [
        {
          code: 'TD.12.2.1.1',
          subTopicName: 'Veri Analizi',
          description: 'Gerçek hayat durumlarıyla ilgili istatistik problemleri çözer.',
          details: [
            'a) Veri toplama, düzenleme, temsil etme ve yorumlama aşamalarına yer verilir.',
            'b) Bir veri grubunu temsil edecek en uygun grafik çeşidi üzerinde durulur. Farklı grafik çeşitlerinin kullanımıyla ilgili uygulamalar yaptırılır.',
            'c) Problemler seçilirken toplumsal duyarlılığı geliştirebilecek çevre bilinci, okuma alışkanlıkları gibi konulara da yer verilir.',
            'ç) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "td_olcme",
      topicName: 'Ölçme (Temel Düzey)',
      gradeLevel: 12,
      learningArea: 'GEOMETRİ',
      sortOrder: 32,
      kazanimlar: [
        {
          code: 'TD.12.3.1.1',
          subTopicName: 'Çevre, Alan ve Hacim Ölçme',
          description: 'Çevre, alan ve hacim ölçmeye yönelik problemler çözer.',
          details: [
            'a) Bir nesnenin belli bir oranda büyütülmüş ya da küçültülmüş çizimini kullanarak, mesafesi, çevre uzunluğu, alanı ve hacmi buldurulur.',
            'b) Bir nesnenin belli bir oranda büyütülmüş veya küçültülmüş çizimleri, ölçekli kâğıt üzerine çizdirilir.',
            'c) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
    {
      examType: "TYT",
      subject: "Matematik",
      topicKey: "td_kati_cisimler",
      topicName: 'Katı Cisimler (Temel Düzey)',
      gradeLevel: 12,
      learningArea: 'GEOMETRİ',
      sortOrder: 33,
      kazanimlar: [
        {
          code: 'TD.12.4.1.1',
          subTopicName: 'Küre ve Silindir',
          description: 'Küre ve dik dairesel silindirin alan ve hacim ölçmeye yönelik problemler çözer.',
          details: [
            'a) Gerçek hayat problemlerine yer verilir.',
            'b) Bilgi ve iletişim teknolojilerinden yararlanılır.',
          ],
          isKeyKazanim: true,
        },
      ],
    },
  ];
}
